name: GetEndpoints

services:
  api:
    build:
      context: ../src
      dockerfile: ../docker/Dockerfile
    network_mode: host
    stop_signal: SIGTERM
    environment:
      FLASK_ENV: production
    volumes:
      - ../src/instance:/app/instance
