services:
  flask-api:
    build: 
      context: ../src
      dockerfile: ../docker/Dockerfile
    ports:
      - 5000:5000
    environment:
      FLASK_ENV: production
    volumes:
      - ../instance:/app/instance
